config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'users#login'
  #root 'login#login'
  get 'login/login' => 'login#login'
  resources :timesheet do
    
  end
  match 'timesheet/export' => 'timesheet#export', :via => :get
  resources :associates
  resources :hrmsdata do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belong_to :timesheet
end

app/models/associate.rb
require 'csv'
class Associate < ApplicationRecord
    def self.to_csv(options = {})
      desired_columns = ["emp_id", "name","timesheet_id", "assignment_id", "chargecode","date", "hours"]
      CSV.generate(options) do |csv|
        csv << desired_columns
        @associates.each do |product|
          csv << product.attributes.values_at(*desired_columns)
        end
      end
    end
end

app/models/hrmsdatum.rb
require 'activerecord-import'
require 'activerecord-import/base'
class Hrmsdatum < ApplicationRecord
end

app/models/timesheet.rb
require 'csv'
class Timesheet < ApplicationRecord
    has_many :assignments
    has_many :associates
    def self.to_csv(options = {})
      desired_columns = ["emp_id", "name","timesheet_id", "assignment_id", "chargecode","date", "hours"]
      CSV.generate(options) do |csv|
        csv << desired_columns
        @associates.each do |product|
          csv << product.attributes.values_at(*desired_columns)
        end
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
    def index
        #associates = @associates
        
        binding.pry
        respond_to do |format|
        format.html
        format.csv { send_data Associate.to_csv(@associates) }
      end
    end
    def user_params
        params.permit(:results)
    end
end

app/controllers/hrmsdata_controller.rb
class HrmsdataController < ApplicationController
  def index
  end
  def import
    spreadsheet = Roo::Spreadsheet.open(params[:file].path)
    header = spreadsheet.row(1)
    @a_list = []
    (2..spreadsheet.last_row).each do |i|
=begin      
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by(id: row["id"]) || new
      product.attributes = row.to_hash
      product.save!
=end
      a = Hrmsdatum.create(associate_name: spreadsheet.row(i)[0],associate_id: spreadsheet.row(i)[1], assignment_id: spreadsheet.row(i)[2],
      job_title: spreadsheet.row(i)[3], jon_id: spreadsheet.row(i)[4], business_id: spreadsheet.row(i)[5], client_id: spreadsheet.row(i)[6],
      work_group: spreadsheet.row(i)[7],hours: spreadsheet.row(i)[8], pay_status: spreadsheet.row(i)[9])
      @a_list << a
    end
    
    render :template => "hrmsdata/index", :locals => {:@list => @a_list}
  end 
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def login
        render 'login/login'
    end
    def home
        render 'login/home'
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to timesheet_index_path
    else
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
end

app/controllers/timesheet_controller.rb
class TimesheetController < ApplicationController
    def new
        @timesheet = Timesheet.new
    end
    def index
        @associates_list = []
        @date = params[:date].to_date
        @sheets = Timesheet.where(timesheet_id: params[:timesheet_id])
        @associates = Associate.where(timesheet_id: params[:timesheet_id])
        @associates = @associates.where('date BETWEEN ? AND ?', @date.beginning_of_week,(@date.beginning_of_week)+6)
        @associates = @associates.order(:emp_id, :assignment_id, :codecharge)
        @loop1 = TEST_VALUE1
        @loop2 = TEST_VALUE2
        
=begin
        @a_list = []
        a=[]
        ag = @associates.order(:emp_id, :assignment_id , :codecharge)
        ag.each_with_index do |value, i|
            if i+1 <= ag.count
              if ag[i].assignment_id == ag[i+1].assignment_id && ag[i].codecharge == ag[i+1].codecharge && ag[i].emp_id == ag[i+1].emp_id
                a<< a[]
                a << a[i+1]
              else
                @a_list << a
                a =[]
                a << a[i+1]
              end
            end
        end 
=end
        
        render :template => "users/index", :locals => { :@associates => @associates, :@date => @date, :@i => @loop1, :@j => @loop2 }
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user= User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
         # Handle a successful save.
        else
            render 'new'
        end
    end
    def login
    end
    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/hrmsdata_helper.rb
module HrmsdataHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/timesheet_helper.rb
module TimesheetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hrmsdata/index.html.erb
<div class = container3 >
  <table>
    <tr>
      <td></td>
      <td>
        <%= form_tag import_hrmsdata_path, multipart: true do %>
          <div class="col-sm-offset-2 col-sm-8">
            <%= file_field_tag :file %>
            <%= submit_tag "Import" %>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <table class = table2>
        <tr>
          <th>Associate Name</th>
          <th>Associate Id</th>
          <th>Assignment Id</th>
          <th>Job Title</th>
          <th>Job Id</th>
          <th>Business Id</th>
          <th>Client Id</th>
          <th>Work group</th>
          <th>Cust Id</th>
          <th>Mon</th>
          <th>Tues</th>
          <th>Wed</th>
          <th>Thur</th>
          <th>Fri</th>
          <th>Sat</th>
          <th>Sun</th>
          <th>Total hours</th>
          <th>Pay Status</th>
        </tr>
        <% if @list.present? %>
          <% @list.each do |i| %>
            <tr>
              <td><%= i.associate_name %></td>
              <td><%= i.associate_id %></td>
              <td><%= i.assignment_id %></td>
              <td><%= i.job_title %></td>
              <td><%= i.jon_id %></td>
              <td><%= i.business_id %></td>
              <td><%= i.client_id %></td>
              <td></td>
              <td><%= i.work_group %></td>
              <td><%= i.hours %></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><%= i.pay_status %></td>
            </tr>
            <% end %>
          <% end %>
        </tr>
      </table>
    </tr>
  </table>
</div>

app/views/login/login.html.erb
<div class = "background">
    <h1>Login</h1>
    <form action= "users" method= "get">
      Username <input type="text"><br><br>
      Password <input type="text"><br><br>
      <input type="submit" value= "Login" >
    </form>
</div>

app/views/statics/statics.html.erb
<table>
  <tr>
    <th>Skills &nbsp; &nbsp; &nbsp;</th>
    <th>Expected-qualifications</th>
    <th>Current-qualifications</th>
  </tr>
</table>